POST http://localhost:3003/api/v1/investments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2ODc5OWQxYjUwYTNhZTA4ZmVmZmI5YTkiLCJlbWFpbCI6ImZlamltMTg4QGdtYWlsLmNvbSIsInJvbGUiOiJpbnZlc3RvciIsImlhdCI6MTc1MzAxMDc4MSwiZXhwIjoxNzUzMDE0MzgxLCJhdWQiOiJsb2NhbGhvc3Q6MzAwMSIsImlzcyI6ImxvY2FsaG9zdDozMDAxIn0.nu2q7UEcsm438fpyNYqioWsieObY6e5ipv-YEdxWYMU

{
    "investmentType": "STOCKS",
    "address": "isgfbiqhd-90cinow",
    "amount": 50000,
    "investmentPlan": "GOLD"
}