export enum InvestmentPlan {
  REGULAR = 'REGULAR',
  INTERMEDIATE = 'INTERMEDIATE',
  EXPERT = 'EXPERT',
  GOLD = 'GOLD',
  PREMIUM = 'PREMIUM',
  EXCECUTIVE = 'EXECUTIVE',
  VIP = 'VIP',
  ULTIMATE = 'ULTIMATE',
}
